CLOUD-2015: Changes for ca-certs
variant-inc/lazy-helm-charts pull request #103
Opened 2022-12-08 17:49 UTC by sdoguparti

# Description

Please look into the description in the JIRA ticket mentioned below

Fixes [#2015](https://drivevariant.atlassian.net/browse/CLOUD-2015)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested this locally using dry-run and also by deploying the changes on dpl and checking the volume mount.

- [x] Sanity Testing

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-08 17:56 UTC, vibindaniel requested changes

2022-12-08 17:56 UTC, vibindaniel commented on charts/variant-cron/values.yaml
> +USXpressCABundle: true
Fix the case please. It should be camelCase

2022-12-08 17:56 UTC, vibindaniel commented on charts/library/templates/_podspec.tpl
> +      {{- if .Values.usxpress_ca_bundle }}
Fix the formatting. Make it consistent like above.

2022-12-08 17:56 UTC, vibindaniel commented on charts/library/templates/_podspec.tpl
> +  {{- if or (len $secrets) (eq .Chart.Name "variant-ui") (.Values.usxpress_ca_bundle)}}
Has this been tested? It feels like the value required by charts and library charts are different.

2022-12-09 14:04 UTC, vibindaniel requested changes

2022-12-09 14:04 UTC, vibindaniel commented on charts/variant-api/values.yaml
> +certMountPath: /etc/ssl/certs/ca-certificates.crt
@sdoguparti if the PR isn't ready, can you move it to draft? I feel that it isn't ready and you are just testing it.

2022-12-09 15:42 UTC, sdoguparti commented on charts/variant-cron/values.yaml
> +USXpressCABundle: true
Fixed the case in my second commit.

2022-12-09 15:44 UTC, sdoguparti commented on charts/library/templates/_podspec.tpl
> +  {{- if or (len $secrets) (eq .Chart.Name "variant-ui") (.Values.usxpress_ca_bundle)}}
Made everything consistent and tested it out with my second commit

2022-12-09 16:50 UTC, vibindaniel commented on charts/variant-api/values.yaml
> +certMountPath: /etc/ssl/certs/ca-certificates.crt
Yes, that looks very good. 
What do you think of certPath instead of the current one?

2022-12-09 17:04 UTC, sdoguparti commented on charts/variant-api/values.yaml
> +certMountPath: /etc/ssl/certs/ca-certificates.crt
I guess that would work or certMountPath is good as well!

2022-12-13 15:09 UTC, zumic96 requested changes
rebase from master as I merged one PR for variant-cron
bump the versions in Chart.yaml for all 4 apps

2022-12-13 15:09 UTC, zumic96 commented on charts/variant-api/README.md
> +| usxpressCACertBundle | bool | `{"certMountPath":"/etc/ssl/certs/ca-certificates.crt","enabled":true}` | If set to true, volume mounts the certificate from the custom-ca-certs secret to a default pa
update this with same style as there is for `service` for all apps
each property gets it's row in table

2022-12-13 15:09 UTC, zumic96 commented on charts/variant-api/ci/default-values.yaml
> +usxpress_ca_bundle:
revert this or update with correct name

2022-12-13 15:09 UTC, zumic96 commented on charts/variant-api/README.md
> +![Version: 2.1.24](https://img.shields.io/badge/Version-2.1.24-informational?style=flat-square)
remove empty space on end of line in all apps, pre-commit fails on that

2022-12-13 15:09 UTC, zumic96 commented on charts/variant-api/values.yaml
> +# -- (bool) If set to true, volume mounts the certificate from the custom-ca-certs secret to a default path. The path can also be changed
update this with same style as there is for `service` for all apps
each property gets it's comment/description

2022-12-13 19:35 UTC, sdoguparti commented on charts/variant-api/README.md
> +![Version: 2.1.24](https://img.shields.io/badge/Version-2.1.24-informational?style=flat-square)
Done

2022-12-13 19:35 UTC, sdoguparti commented on charts/variant-api/ci/default-values.yaml
> +usxpress_ca_bundle:
Done

2022-12-15 16:04 UTC, sdoguparti commented on charts/variant-api/README.md
> +| usxpressCACertBundle | bool | `{"certMountPath":"/etc/ssl/certs/ca-certificates.crt","enabled":true}` | If set to true, volume mounts the certificate from the custom-ca-certs secret to a default pa
Done

2022-12-16 14:38 UTC, zumic96 approved these changes

2022-12-16 19:28 UTC, merged