CLOUD-2408 [Placeholder] Update Lazy-Helm Charts
variant-inc/lazy-helm-charts pull request #123
Opened 2023-10-27 14:23 UTC by vibindaniel

# Description

First run of routes helm chart

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Sanity Testing

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-30 10:32 UTC, zumic96 requested changes
I had trouble getting `environment` to work, looks like the if statement is not working as expected.

2023-10-30 10:32 UTC, zumic96 commented on charts/routes/templates/virtualservice.yaml
> +              regex: .*
Since we're just checking for existance of header we can write it like described [here](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest).

If the value is empty and only the name of header is specified, presence of the header is checked. To provide an empty value, use {}, for example:
```
 - match:
   - headers:
       Authorization: {}
```

2023-10-30 10:32 UTC, zumic96 commented on charts/routes/templates/_domains.tpl
> +{{ printf "%s.internal.%s%s" (index .Values.subdomains 0) $environment $domain | quote }}
```
{{- printf "%s.internal.%s%s" (index .Values.subdomains 0) $environment $domain | quote }}
```

2023-10-30 12:57 UTC, vibindaniel commented on charts/routes/values.yaml
> +subdomains: []
I don't think `required` will work in this scenario. It will work for null or empty values. In this case, `subdomains` is neither null or, empty. It is a list with 0 elements.

2023-11-02 08:37 UTC, zumic96 approved these changes

2023-11-13 13:56 UTC, zumic96 requested changes

2023-11-13 13:56 UTC, zumic96 commented on .github/workflows/pre-commit.yml
> +          python-version: '3.10'
We can go back to 3.12 since switching to shellcheck

2023-11-13 13:56 UTC, zumic96 commented on charts/routes/templates/virtualservice.yaml
> +{{- if and .Values.public.enabled (len .Values.public.privatePaths) }}
Remove (len .Values.public.privatePaths) condition as default values are now embedded in this template.
This way if someone sets privatePaths to empty list there will be no redirects.

2023-11-13 13:56 UTC, zumic96 commented on charts/routes/values.yaml
> +  privatePaths:
Adding to the comment in virtualservice, I believe this default values can be removed from values file.

2023-11-14 11:45 UTC, closed without merging