Lazy 86 Variant API VS
variant-inc/lazy-helm-charts pull request #15
Opened 2021-04-01 16:42 UTC by salyateem13

Here we add a new chart for API access to apps. We follow a new url convention of api.internal.apps.{{ .Values.istio.ingress.host}} and api.internal.{{ .Values.istio.ingress.host}} for private access via VPN.

If {{ .Values.istio.ingress.public}} is true, then public endpoints are exposed to api.{{ .Values.istio.ingress.host}} and api.apps.{{ .Values.istio.ingress.host}} 

the api.*.apps.{{ .Values.istio.ingress.host}} will be deprecated once a Hosted Zone is setup for api.*.{{ .Values.istio.ingress.host}}. Therefore, api.*.{{ .Values.istio.ingress.host}} will not work when testing this change, only api.*.apps.{{ .Values.istio.ingress.host}} will

2021-04-02 03:02 UTC, vibindaniel requested changes

2021-04-02 03:02 UTC, vibindaniel commented on charts/variant-api/templates/NOTES.txt
> +{{- end}}
Can you also list the APIs that will not be available for public access?

2021-04-02 03:03 UTC, vibindaniel commented
Let us update the iaac repository to allow api.<domain> to api.apps.<domain>. I'll create a ticket for this.

2021-04-05 14:03 UTC, salyateem13 commented on charts/variant-api/templates/NOTES.txt
> +{{- end}}
Yep, will get that included

2021-04-05 20:46 UTC, salyateem13 commented
> Let us update the iaac repository to allow api. to api.apps.. I'll create a ticket for this.

I see you merged that PR. We still need a hosted zone for the cluster before we can remove api.apps.* from the chart, correct?

2021-04-06 14:17 UTC, vibindaniel approved these changes

2021-04-06 16:35 UTC, merged