Renamed variant-services-deployment
variant-inc/lazy-helm-charts pull request #17
Opened 2021-04-16 17:29 UTC by salyateem13

To test, cd to variant-ui chart and edit the values.yaml to enable istio. Configure the hosts and backend, and install the chart.

`helm install test-release . -n test --create-namespace`

Confirm install of chart with multiple host names.

2021-04-16 18:12 UTC, vibindaniel requested changes

2021-04-16 18:12 UTC, vibindaniel commented on charts/variant-ui/templates/NOTES.txt
> +{{- end}}
Can you add the part saying "Make sure that the hosts added have a proper certificate in the EKS cluster"

2021-04-16 19:42 UTC, salyateem13 commented on charts/variant-ui/templates/NOTES.txt
> +{{- end}}
Yep

2021-04-16 19:43 UTC, salyateem13 commented on charts/variant-ui/templates/NOTES.txt
> +{{- end}}
Do we have docs on how to do that?

2021-04-23 11:09 UTC, vibindaniel approved these changes

2021-04-23 13:28 UTC, merged