F/cloud 1742 selector labels
variant-inc/lazy-helm-charts pull request #78
Opened 2022-05-24 18:20 UTC by rchengvariant

# Description

https://drivevariant.atlassian.net/browse/CLOUD-1742

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Sanity Testing

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-25 13:03 UTC, vibindaniel requested changes

2022-05-25 13:03 UTC, vibindaniel commented on charts/library/templates/_chart.tpl
> -app: {{ .Release.Name }}
Why are these lines removed?

2022-05-25 13:16 UTC, rchengvariant commented on charts/library/templates/_chart.tpl
> -app: {{ .Release.Name }}
Chart Labels include selector labels already. It would be there twice if not removed.

https://github.com/variant-inc/lazy-helm-charts/pull/78/files#diff-ac13b33ec0f0927a2f1ec891cd13091a47edeece15380689859ed93a72349d0fL22

2022-05-25 13:19 UTC, vibindaniel commented on charts/library/templates/_chart.tpl
> -app: {{ .Release.Name }}
Can you show with images that it shows up twice if not removed?

2022-05-25 13:34 UTC, vibindaniel approved these changes

2022-05-26 17:02 UTC, LeeHughsVariant approved these changes
Update chart versions, then LGTM

2022-05-26 18:54 UTC, merged